#!/usr/bin/env fish

if [ ! (which git) ]
    echo "`git` is required for installation.  Please try again after installing an accessible git binary."
    exit 1
end

set -q XDG_CONFIG_HOME
    and set FISH_PATH "$XDG_CONFIG_HOME/fish"
    or set FISH_PATH "$HOME/.config/fish"

[ -d "$FISH_PATH/triton/github.com/dukejones/triton" ]
    or git clone https://github.com/dukejones/triton.git "$FISH_PATH/triton/github.com/dukejones/triton"

mkdir -p "$FISH_PATH/functions"
[ -f "$FISH_PATH/functions/triton.fish" ]
    or ln -s "$FISH_PATH/triton/github.com/dukejones/triton/functions/triton.fish" "$FISH_PATH/functions/"

exec fish

echo "Welcome to Triton!  To bootstrap a nice set of default fish configuration files you may wish to run:"
echo
echo "triton bootstrap"
echo
echo "Triton: calling forth packages from the primordial ocean of the internet for ultimate shell happiness. 👑"
